// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYZ4alECHEjhj_wWXeccQUNw3Vg-PClbA',
    appId: '1:984295087164:web:e7234e24914861af367739',
    messagingSenderId: '984295087164',
    projectId: 'elshosh-first-project-3dbf7',
    authDomain: 'elshosh-first-project-3dbf7.firebaseapp.com',
    storageBucket: 'elshosh-first-project-3dbf7.firebasestorage.app',
    measurementId: 'G-3Q12442GDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhWNTp8-DQZfAUMN0mzdB3kEC0mMVHmY4',
    appId: '1:984295087164:android:9a6f48b0f8a08869367739',
    messagingSenderId: '984295087164',
    projectId: 'elshosh-first-project-3dbf7',
    storageBucket: 'elshosh-first-project-3dbf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmfiUx_aD6bSXIfGbvoxAHj8rLtUILDm0',
    appId: '1:984295087164:ios:3cf45f73aa84db4b367739',
    messagingSenderId: '984295087164',
    projectId: 'elshosh-first-project-3dbf7',
    storageBucket: 'elshosh-first-project-3dbf7.firebasestorage.app',
    iosBundleId: 'com.elshosh.myfirstproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmfiUx_aD6bSXIfGbvoxAHj8rLtUILDm0',
    appId: '1:984295087164:ios:3cf45f73aa84db4b367739',
    messagingSenderId: '984295087164',
    projectId: 'elshosh-first-project-3dbf7',
    storageBucket: 'elshosh-first-project-3dbf7.firebasestorage.app',
    iosBundleId: 'com.elshosh.myfirstproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYZ4alECHEjhj_wWXeccQUNw3Vg-PClbA',
    appId: '1:984295087164:web:f990f37f92a2e67a367739',
    messagingSenderId: '984295087164',
    projectId: 'elshosh-first-project-3dbf7',
    authDomain: 'elshosh-first-project-3dbf7.firebaseapp.com',
    storageBucket: 'elshosh-first-project-3dbf7.firebasestorage.app',
    measurementId: 'G-M877LCM6WL',
  );
}
